### PR TITLE
Updated broken link to tutorial on Phpocean.com ( now lancecourse.com )

### PR DESCRIPTION
**Pull request by zooboole**
The link to the tutorial "Create your first Desktop Application with PHP and PHP Desktop" has changed. The site phpocean.com is now lancecourse.com. 

The new link is https://lancecourse.com/en/howto/create-your-first-desktop-application-with-php-and-php-desktop

### CODE REVIEW

**Comment by cztomczak** [comment]
@zooboole This link also doesn't work for me.

**Comment by zooboole** [comment]
Can you access the other pages of the site? Also, it underwent some maintenance a few days ago, Maybe you checked in that period. Kindly let me know. Thanks

**Comment by 2braincells2go** [comment]
This is all iI see and adblocker is off:

image

**Comment by zooboole** [comment]
Great. That proves that the site is up and available in your region as well. The message you are seeing indicates that you have an adblocker. By disabling it you should have the content. Nonetheless, I am going to update that part of the website and make the alert float over the content.

**Comment by 2braincells2go** [comment]
@zooboole As I stated, I do not have adblocker active on browser. Anyway, best of luck with your site and tutorial.

**Comment by zooboole** [comment]
Wow, I did not notice that you mentioned that your adblocker was off. 
I have fixed it anyway. The article is fully accessible now. And I sincerely apologize for the back and forth. 

php_desktop

**Comment by cztomczak** [comment]
Works for me now. Thank you.

**Comment by cztomczak** [comment]
Actually the link in README doesn't work and is different from https://lancecourse.com/en/howto/create-your-first-desktop-application-with-php-and-php-desktop . Please update the PR.

**Pull request merged**
